type Query {
  # say hello to someone
  list: [Info]
}

type Mutation {
  add: Info
}

type Info {
  id: ID!
  items: [Item]
}

type Item {
  id: String
  name: Names
}

type Names {
  english: String
  japanese: String
  chinese: String
}